include(InstallRequiredSystemLibraries)

set(CPACK_PACKAGE_NAME "solver")

set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "0")

set(CPACK_PACKAGE_CONTACT "margo190607@gmail.com")

set(CPACK_PACKAGE_DESCRIPTION_SUMMARY
    "Solver application")

set(CPACK_PACKAGE_DESCRIPTION_FILE
    ${CMAKE_CURRENT_SOURCE_DIR}/DESCRIPTION)

set(CPACK_RESOURCE_FILE_LICENSE
    ${CMAKE_CURRENT_SOURCE_DIR}/LICENSE)

set(CPACK_GENERATOR "ZIP;TGZ")

include(CPack)
